-- MySQL Script generated by MySQL Workbench
-- qua 24 nov 2021 00:17:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aula_php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aula_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aula_php` DEFAULT CHARACTER SET utf8 ;
USE `aula_php` ;

-- -----------------------------------------------------
-- Table `aula_php`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula_php`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `ultimo_acesso` DATETIME NULL,
  `criacao` DATETIME NOT NULL DEFAULT now(),
  `email` VARCHAR(64) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `senha_assinatura` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aula_php`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula_php`.`modulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aula_php`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula_php`.`permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inserir` TINYINT NOT NULL DEFAULT 0,
  `atualizar` TINYINT NOT NULL DEFAULT 0,
  `selecionar` TINYINT NOT NULL DEFAULT 0,
  `deletar` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aula_php`.`usuario_acesso_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula_php`.`usuario_acesso_modulo` (
  `usuario_id` INT NOT NULL,
  `modulo_id` INT NOT NULL,
  `permissao_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `modulo_id`),
  INDEX `fk_usuario_has_modulo_modulo1_idx` (`modulo_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_modulo_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_acesso_modulo_permissao1_idx` (`permissao_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_modulo_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `aula_php`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_modulo_modulo1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `aula_php`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_acesso_modulo_permissao1`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `aula_php`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;